const conversations = [
  { name: "Toronto crew", preview: "Lena shared a location", active: true, color: "blue" },
  { name: "Family", preview: "Voice message · 0:18", color: "purple" },
  { name: "Petersburg trip", preview: "Meet at the blue spot", color: "green" }
];

export default function Home() {
  return <main className="site-demo"><aside className="demo-rail"><div className="logo">K</div><button className="active">◉<span>Chat</span></button><button>⌖<span>Map</span></button><button>◎<span>Groups</span></button><button>◇<span>Profile</span></button><div className="rail-bottom">AU</div></aside><section className="demo-conversations"><header><div><small>KRASUN</small><h1>Messages</h1></div><button>＋</button></header><div className="demo-search">⌕ &nbsp; Search conversations</div><p className="label">Direct messages</p>{conversations.map((item) => <article key={item.name} className={item.active ? "active" : ""}><span className={`person ${item.color}`}>{item.name[0]}</span><div><strong>{item.name}</strong><small>{item.preview}</small></div><time>{item.active ? "now" : "12:42"}</time></article>)}</section><section className="demo-chat"><header><span className="person blue">T</span><div><strong>Toronto crew</strong><small><i /> 4 people online</small></div><button>•••</button></header><div className="demo-messages"><div className="date">Today</div><article><b>Lena</b><p>I found the quietest place near campus.</p><time>14:18</time></article><article className="map-message"><div className="mini-map"><span>●</span><i /></div><div><b>Robarts Library</b><p>Shared spot · 130 St George St</p><button>Open on Map ↗</button></div></article><article className="mine"><p>Perfect. I’m walking over now.</p><time>14:21</time></article><div className="typing"><i/><i/><i/> Lena is typing…</div></div><footer><button>＋</button><span>Message Toronto crew</span><button className="send">➤</button></footer></section><aside className="demo-map"><div className="map-grid"/><header><small>LIVE GROUP MAP</small><strong>Toronto crew</strong></header><div className="route"/><span className="pin p-one">AU</span><span className="pin p-two">L</span><span className="spot">◆</span><div className="route-info"><small>WALKING ROUTE · SNAPSHOT</small><strong>Robarts Library</strong><div><b>8 min</b><b>0.6 km</b></div></div></aside></main>;
}
