import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowRight, Copy, Map, MessageCircle, Plus, Users } from "lucide-react";
import type { GroupJoinMode } from "@krasun/shared-types";
import { apiFetch } from "../../services/api";
import { useGroups } from "./useGroups";

export function GroupsPage() {
  const { groups, loading, error, reload } = useGroups();
  const [modal, setModal] = useState<"create" | "join" | null>(null);
  const navigate = useNavigate();
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const data = await apiFetch<{ group: { id: string } }>("/api/groups", { method: "POST", body: JSON.stringify({ name: form.get("name"), description: form.get("description"), joinMode: form.get("joinMode") as GroupJoinMode }) }); setModal(null); reload(); navigate(`/groups/${data.group.id}`); }
  async function join(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await apiFetch("/api/groups/join", { method: "POST", body: JSON.stringify({ code: form.get("code") }) }); setModal(null); reload(); }
  return <main className="page groups-page"><header className="page-header"><div><p className="eyebrow">Your circles</p><h1>Groups</h1><p>Every group has one shared chat, one shared map and explicit membership.</p></div><div className="header-actions"><button className="button secondary" onClick={() => setModal("join")}>Join group</button><button className="button primary" onClick={() => setModal("create")}><Plus size={17} /> Create group</button></div></header>
    {loading ? <div className="center-card"><span className="loader" /> Loading groups…</div> : error ? <div className="error-banner">{error}</div> : groups.length === 0 ? <div className="empty-state"><span><Users /></span><h2>Start your first circle</h2><p>Create a group for friends, family or a trip. The creator becomes owner.</p><button className="button primary" onClick={() => setModal("create")}>Create group</button></div> : <div className="group-grid">{groups.map((group) => <article className="group-card" key={group.id}><div className="group-card-top"><span className="group-avatar">{group.name[0]?.toUpperCase()}</span><span className="role-pill">{group.role}</span></div><h2>{group.name}</h2><p>{group.description || "A shared Krasun circle."}</p><div className="group-meta"><span><Users size={15} /> {group.memberCount}</span><button onClick={() => void navigator.clipboard.writeText(group.inviteCode)} title="Copy invite code"><Copy size={14} /> {group.inviteCode}</button></div><div className="group-actions"><Link to={`/groups/${group.id}/chat`} onClick={() => localStorage.setItem("krasun:last-group", group.id)}><MessageCircle /> Chat</Link><Link to={`/groups/${group.id}/map`} onClick={() => localStorage.setItem("krasun:last-group", group.id)}><Map /> Map</Link><Link to={`/groups/${group.id}`}><ArrowRight /></Link></div></article>)}</div>}
    {modal && <div className="modal-backdrop" role="presentation"><form className="modal-card" onSubmit={modal === "create" ? create : join}><button type="button" className="modal-close" onClick={() => setModal(null)}>×</button><p className="eyebrow">{modal === "create" ? "New circle" : "Invite"}</p><h2>{modal === "create" ? "Create a group" : "Join a group"}</h2>{modal === "create" ? <><label>Group name<input name="name" required minLength={2} maxLength={80} autoFocus /></label><label>Description<textarea name="description" maxLength={500} /></label><label>Join mode<select name="joinMode" defaultValue="OPEN"><option value="OPEN">Open</option><option value="APPROVAL_REQUIRED">Approval required</option><option value="INVITE_ONLY">Invite only</option></select></label></> : <label>Invite code<input name="code" required minLength={4} maxLength={32} autoFocus /></label>}<button className="button primary wide">{modal === "create" ? "Create group" : "Join"}</button></form></div>}
  </main>;
}
